CREATE SCHEMA IF NOT EXISTS db_rwr
  CHAR SET = utf8
  COLLATE utf8_general_ci;

USE db_rwr;

DROP TABLE IF EXISTS SEEKER_PHONE;
DROP TABLE IF EXISTS SEEKER_EMAIL;
DROP TABLE IF EXISTS SEEKER_IMS;
DROP TABLE IF EXISTS SEEKER_SKILLS;
DROP TABLE IF EXISTS SEEKER;
DROP TABLE IF EXISTS IMS_TYPE;
DROP TABLE IF EXISTS SKILLS_TYPE;

CREATE TABLE SEEKER (
  id                INTEGER     NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name        VARCHAR(32) NOT NULL,
  last_name         VARCHAR(32) NOT NULL,
  date_of_addition  DATE        NOT NULL,
  date_of_interview DATE        NOT NULL
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;


CREATE TABLE SEEKER_PHONE (
  id           INTEGER     NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phone_number VARCHAR(32) NOT NULL UNIQUE,
  seeker_id    INTEGER     NOT NULL
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE SEEKER_EMAIL (
  id        INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email     VARCHAR(255) UNIQUE,
  seeker_id INTEGER NOT NULL
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE SEEKER_IMS (
  id          INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ims_type_id INTEGER      NOT NULL,
  ims_login   VARCHAR(255) NOT NULL UNIQUE,
  seeker_id   INTEGER      NOT NULL
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE IMS_TYPE (
  id   INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(128) UNIQUE
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

ALTER TABLE SEEKER_PHONE ADD CONSTRAINT fk_seekerPhone FOREIGN KEY (seeker_id) REFERENCES SEEKER (id);
ALTER TABLE SEEKER_EMAIL ADD CONSTRAINT fk_seekerEmail FOREIGN KEY (seeker_id) REFERENCES SEEKER (id);
ALTER TABLE SEEKER_IMS ADD CONSTRAINT fk_seekerIms FOREIGN KEY (seeker_id) REFERENCES SEEKER (id);
ALTER TABLE SEEKER_IMS ADD CONSTRAINT fk_ImsType FOREIGN KEY (ims_type_id) REFERENCES IMS_TYPE (id);


CREATE TABLE SEEKER_SKILLS (
  id            INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  skill_type_id INTEGER NOT NULL,
  skill_rating  INTEGER          DEFAULT 0,
  seeker_id     INTEGER NOT NULL
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE SKILLS_TYPE (
  id   INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(128) UNIQUE
)
  ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

ALTER TABLE SEEKER_SKILLS ADD CONSTRAINT fk_seekerSkills FOREIGN KEY (seeker_id) REFERENCES SEEKER (id);
ALTER TABLE SEEKER_SKILLS ADD CONSTRAINT fk_skillType FOREIGN KEY (skill_type_id) REFERENCES SEEKER_SKILLS (id);

